class CountryCode {
  final String code;
  final String country;

  CountryCode(this.code, this.country);
}

// 국가 번호와 이름 목록
List<CountryCode> countryCodes = [
  CountryCode('+93', '아프가니스탄'),
  CountryCode('+355', '알바니아'),
  CountryCode('+213', '알제리'),
  CountryCode('+1', '앵귈라'),
  CountryCode('+1', '앤티가 바부다'),
  CountryCode('+54', '아르헨티나'),
  CountryCode('+374', '아르메니아'),
  CountryCode('+297', '아루바'),
  CountryCode('+61', '호주'),
  CountryCode('+43', '오스트리아'),
  CountryCode('+994', '아제르바이잔'),
  CountryCode('+1', '바하마'),
  CountryCode('+973', '바레인'),
  CountryCode('+880', '방글라데시'),
  CountryCode('+1', '바베이도스'),
  CountryCode('+32', '벨기에'),
  CountryCode('+501', '벨리즈'),
  CountryCode('+229', '베냉'),
  CountryCode('+975', '부탄'),
  CountryCode('+591', '볼리비아'),
  CountryCode('+387', '보스니아 헤르체고비나'),
  CountryCode('+267', '보츠와나'),
  CountryCode('+55', '브라질'),
  CountryCode('+246', '브리티시 인디언 오션 영토'),
  CountryCode('+1', '브리티시 버진 아일랜드'),
  CountryCode('+673', '브루나이'),
  CountryCode('+359', '불가리아'),
  CountryCode('+226', '부르키나파소'),
  CountryCode('+257', '부룬디'),
  CountryCode('+855', '캄보디아'),
  CountryCode('+237', '카메룬'),
  CountryCode('+1', '캐나다'),
  CountryCode('+238', '카보베르데'),
  CountryCode('+345', '케이맨 제도'),
  CountryCode('+236', '중앙 아프리카 공화국'),
  CountryCode('+61', '차드'),
  CountryCode('+56', '칠레'),
  CountryCode('+86', '중국'),
  CountryCode('+57', '콜롬비아'),
  CountryCode('+242', '콩고'),
  CountryCode('+682', '쿡 제도'),
  CountryCode('+506', '코스타리카'),
  CountryCode('+225', '코트디부아르'),
  CountryCode('+385', '크로아티아'),
  CountryCode('+53', '쿠바'),
  CountryCode('+599', '큐라사오'),
  CountryCode('+357', '사이프러스'),
  CountryCode('+420', '체코'),
  CountryCode('+45', '덴마크'),
  CountryCode('+253', '지부티'),
  CountryCode('+1', '도미니카'),
  CountryCode('+1809', '도미니카 공화국'),
  CountryCode('+593', '에콰도르'),
  CountryCode('+20', '이집트'),
  CountryCode('+503', '엘살바도르'),
  CountryCode('+240', '적도 기니'),
  CountryCode('+291', '에리트레아'),
  CountryCode('+372', '에스토니아'),
  CountryCode('+251', '에티오피아'),
  CountryCode('+500', '포클랜드 제도'),
  CountryCode('+298', '페로 제도'),
  CountryCode('+679', '피지'),
  CountryCode('+358', '핀란드'),
  CountryCode('+33', '프랑스'),
  CountryCode('+594', '프랑스 기아나'),
  CountryCode('+689', '프랑스령 폴리네시아'),
  CountryCode('+241', '가봉'),
  CountryCode('+220', '감비아'),
  CountryCode('+995', '조지아'),
  CountryCode('+49', '독일'),
  CountryCode('+233', '가나'),
  CountryCode('+350', '지브롤터'),
  CountryCode('+30', '그리스'),
  CountryCode('+299', '그린란드'),
  CountryCode('+1', '그레나다'),
  CountryCode('+590', '과들루프'),
  CountryCode('+502', '과테말라'),
  CountryCode('+44', '영국'),
  CountryCode('+224', '기니'),
  CountryCode('+245', '기니비사우'),
  CountryCode('+592', '가이아나'),
  CountryCode('+509', '아이티'),
  CountryCode('+504', '온두라스'),
  CountryCode('+852', '홍콩'),
  CountryCode('+36', '헝가리'),
  CountryCode('+354', '아이슬란드'),
  CountryCode('+91', '인도'),
  CountryCode('+62', '인도네시아'),
  CountryCode('+98', '이란'),
  CountryCode('+964', '이라크'),
  CountryCode('+353', '아일랜드'),
  CountryCode('+972', '이스라엘'),
  CountryCode('+39', '이탈리아'),
  CountryCode('+1', '자메이카'),
  CountryCode('+81', '일본'),
  CountryCode('+962', '요르단'),
  CountryCode('+7', '카자흐스탄'),
  CountryCode('+254', '케냐'),
  CountryCode('+686', '키리바시'),
  CountryCode('+965', '쿠웨이트'),
  CountryCode('+996', '키르기스스탄'),
  CountryCode('+856', '라오스'),
  CountryCode('+371', '라트비아'),
  CountryCode('+961', '레바논'),
  CountryCode('+266', '레소토'),
  CountryCode('+231', '라이베리아'),
  CountryCode('+218', '리비아'),
  CountryCode('+423', '리히텐슈타인'),
  CountryCode('+370', '리투아니아'),
  CountryCode('+352', '룩셈부르크'),
  CountryCode('+261', '마다가스카르'),
  CountryCode('+265', '말라위'),
  CountryCode('+60', '말레이시아'),
  CountryCode('+960', '몰디브'),
  CountryCode('+223', '말리'),
  CountryCode('+356', '몰타'),
  CountryCode('+692', '미크로네시아'),
  CountryCode('+261', '모리셔스'),
  CountryCode('+222', '모리타니'),
  CountryCode('+52', '멕시코'),
  CountryCode('+691', '미크로네시아'),
  CountryCode('+373', '몰도바'),
  CountryCode('+377', '모나코'),
  CountryCode('+976', '몽골'),
  CountryCode('+382', '몬테네그로'),
  CountryCode('+1664', '네덜란드령 앤틉과 바부다'),
  CountryCode('+227', '니제르'),
  CountryCode('+234', '나이지리아'),
  CountryCode('+683', '니우에'),
  CountryCode('+850', '북한'),
  CountryCode('+47', '노르웨이'),
  CountryCode('+968', '오만'),
  CountryCode('+92', '파키스탄'),
  CountryCode('+680', '팔라우'),
  CountryCode('+507', '파나마'),
  CountryCode('+675', '파푸아뉴기니'),
  CountryCode('+595', '파라과이'),
  CountryCode('+51', '페루'),
  CountryCode('+63', '필리핀'),
  CountryCode('+48', '폴란드'),
  CountryCode('+351', '포르투갈'),
  CountryCode('+1', '푸에르토리코'),
  CountryCode('+974', '카타르'),
  CountryCode('+40', '루마니아'),
  CountryCode('+7', '러시아'),
  CountryCode('+250', '르완다'),
  CountryCode('+685', '사모아'),
  CountryCode('+378', '산마리노'),
  CountryCode('+239', '상투메프린시페'),
  CountryCode('+966', '사우디아라비아'),
  CountryCode('+221', '세네갈'),
  CountryCode('+381', '세르비아'),
  CountryCode('+248', '세이셸'),
  CountryCode('+232', '시에라리온'),
  CountryCode('+65', '싱가포르'),
  CountryCode('+421', '슬로바키아'),
  CountryCode('+386', '슬로베니아'),
  CountryCode('+677', '솔로몬 제도'),
  CountryCode('+252', '소말리아'),
  CountryCode('+27', '남아프리카 공화국'),
  CountryCode('+34', '스페인'),
  CountryCode('+94', '스리랑카'),
  CountryCode('+211', '남수단'),
  CountryCode('+249', '수단'),
  CountryCode('+597', '수리남'),
  CountryCode('+268', '스와질란드'),
  CountryCode('+46', '스웨덴'),
  CountryCode('+41', '스위스'),
  CountryCode('+963', '시리아'),
  CountryCode('+886', '대만'),
  CountryCode('+992', '타지키스탄'),
  CountryCode('+255', '탄자니아'),
  CountryCode('+66', '태국'),
  CountryCode('+670', '동티모르'),
  CountryCode('+228', '토고'),
  CountryCode('+690', '투발루'),
  CountryCode('+676', '통가'),
  CountryCode('+1', '트리니다드 토바고'),
  CountryCode('+216', '튀니지'),
  CountryCode('+90', '터키'),
  CountryCode('+993', '투르크메니스탄'),
  CountryCode('+1', '미국'),
  CountryCode('+998', '우즈베키스탄'),
  CountryCode('+678', '바누아투'),
  CountryCode('+58', '베네수엘라'),
  CountryCode('+84', '베트남'),
  CountryCode('+681', '웨이크 제도'),
  CountryCode('+1', '미국령 버진 아일랜드'),
  CountryCode('+82', '대한민국')
];
